# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        python-version: [ 3.8, 3.9, "3.10", 3.11 ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U build setuptools wheel twine cibuildwheel
    - name: Normal Build
      run: |
        python -m build
    - name: Build wheels
      env:
        CIBW_BEFORE_ALL_LINUX: yum install -y libffi-dev
      run: python -m cibuildwheel --output-dir wheelhouse
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/* --skip-existing
        twine upload wheelhouse/* --skip-existing


